# ---- App metadata (used across platforms) ----
[application]
# App name (what users see under the icon, unless overridden below)
name = "Konan"
# Optional, but handy if you mostly target iOS
default_platform = "ios"

# iOS-specific app settings
[application.ios]
# Set this to match your Xcode/iOS SDK; 15+ is generally safe
minimum_ios_version = "15.0"

# ---- Web bits (optional; keep if you also build for web) ----
[web.app]
title = "konan_mobile"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

# ---- Bundle/signing metadata ----
[bundle]
# MUST be a reverse-DNS string (not just "konan")
# Use your own domain or a placeholder you control
identifier = "com.ces.konan"
publisher  = "Cesar"

# iOS-specific bundle settings (optional but nice to have)
[bundle.ios]
# Shown on the home screen (falls back to [application].name)
display_name = "Konan"
# If you have icons, list them (single 1024x1024 works; Xcode will resize)
# icon = ["assets/AppIcon1024.png"]

# If you need permissions later, add usage descriptions here (examples):
# privacy_camera_usage_description   = "Needed to scan receipts."
# privacy_photos_usage_description   = "Save images."
# privacy_microphone_usage_description = "Voice notes."

